version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - $PWD/openapi:/usr/share/nginx/html/openapi/
    environment:
      API_URL: ./openapi/openapi.yml
