openapi: 3.1.0
info:
  title: Swagger サンプル - OpenAPI 3.0
  description: >-
    ## Swaggerのサンプルプロジェクトです。
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://sample.swagger.io/api/
tags:
  - name: pet
    description: ペット
paths:
  /pet:
    $ref: "paths/pet/index.yml"
components:
  schemas:
    Pet:
      $ref: "schemas/pet.yml"
    Tag:
      $ref: "schemas/tag.yml"
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
